# mplPars = {'text.usetex': True,
#            'axes.labelsize': 'large',
#            'axes.titlesize': 24,
#            'font.family': 'sans-serif',
#            'font.sans-serif': 'computer modern bright',
#            'font.size': 24,
#            'font.weight': 'black',
#            'xtick.labelsize': 20,
#            'ytick.labelsize': 20,
#            'legend.fontsize': 20,
#            'legend.frameon': True,
#            'legend.framealpha': 0,
#            'legend.fancybox': True,
#            'text.latex.preamble': r'\usepackage{cmbright}',
#            "lines.linewidth": 3,
#            "lines.markersize": 10
#            }

mplPars = {'text.usetex': True,
           'axes.labelsize': 'large',
           'axes.titlesize': 32,
           'font.family': 'sans-serif',
           'font.sans-serif': 'computer modern bright',
           'font.size': 32,
           'font.weight': 'black',
           'xtick.labelsize': 26,
           'ytick.labelsize': 26,
           'legend.fontsize': 26,
           'legend.frameon': True,
           'legend.framealpha': 0,
           'legend.fancybox': True,
           'text.latex.preamble': r'\usepackage{cmbright}',
           "lines.linewidth": 3,
           "lines.markersize": 10
           }